==> "this is a string"
==> " "
==> "another string with some scheme char inside #\t "
==> "another string with some scheme char inside #\space "
==> "another string with some scheme parenthesis () "
==> "another string with some scheme parenthesis ()  ( )"
